### ISSUE TITLE
Errors when using Python 3

### ISSUE THREAD

**Issue by alinbalutoiu** [Microsoft/pal#65]
Error when using Python 3:
```
Traceback (most recent call last):
  File "/home/ubuntu/a_latest/build-omi-script-provider/pal/installer/InstallBuilder/installbuilder.py", line 3, in <module>
    import datafileparser
  File "/home/ubuntu/a_latest/build-omi-script-provider/pal/installer/InstallBuilder/datafileparser.py", line 310
    sectionPriority = m.group(1)
    ^
IndentationError: expected an indented block
```
and 
```
Traceback (most recent call last):
  File "/home/ubuntu/a_latest/build-omi-script-provider/pal/installer/InstallBuilder/installbuilder.py", line 4, in <module>
    import linuxrpm
  File "/home/ubuntu/a_latest/build-omi-script-provider/pal/installer/InstallBuilder/linuxrpm.py", line 2, in <module>
    import scxutil
  File "/home/ubuntu/a_latest/build-omi-script-provider/pal/installer/InstallBuilder/scxutil.py", line 21
    print "Symbolic link: " + srcname + " -> " + dstname
                          ^
SyntaxError: Missing parentheses in call to 'print'
```
In Python 3, mixing tabs with spaces is a syntax error.
Also, it's required for print to have parenthesis around the string which will be printed.

None of these changes affect Python 2 in any way.

**Comment by jeffaco** [comment]
Associated PR merged, closing this issue.
